[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "RUF", "C4", "BLE", "FURB", "PLC", "PIE", "TRY", "EXE"]
ignore = ["E402", "E501", "B008", "TRY003", "B905", "BLE001", "RUF001", "PLC0415", "TRY004", "PLC0206", "B017", "B023", "TRY300", "SIM102", "B904", "RUF012"]
