[lint]
select = ["E", "F", "UP", "B", "C4", "SIM", "PLC", "I", "BLE", "TRY", "RUF", "FURB", "PIE", "EXE", "PLR"]
ignore = ["E402", "B008", "BLE001", "PLR2004", "TRY003", "PLR0913", "E501", "PLC0415", "PLR0912", "B023", "PLR0915", "RUF001", "EXE001", "B017", "TRY300", "SIM102", "RUF012", "PLR0911", "B904", "TRY004", "PLC0206"]
