name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving this project!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is and why it is needed.
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: false
