name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
