#!/usr/bin/env python3
"""
Synchronizes documentation with the current state of the codebase.
"""

import ast
import os


def get_docstring(node):
    return ast.get_docstring(node)


def generate_api_docs(repo_root):
    api_docs = []
    api_docs.append("# API Documentation")
    api_docs.append("This document is auto-generated by `tools/docs_sync.py`.\n")

    for root, _, files in os.walk(repo_root):
        if (
            ".venv" in root
            or "node_modules" in root
            or ".git" in root
            or "tests" in root
        ):
            continue
        for file in files:
            if file.endswith(".py"):
                filepath = os.path.join(root, file)
                rel_path = os.path.relpath(filepath, repo_root)

                try:
                    with open(filepath, "r", encoding="utf-8") as f:
                        content = f.read()
                    tree = ast.parse(content)

                    file_has_docs = False
                    file_docs = [f"## `{rel_path}`\n"]

                    module_doc = ast.get_docstring(tree)
                    if module_doc:
                        file_docs.append(f"{module_doc}\n")
                        file_has_docs = True

                    for node in ast.walk(tree):
                        if isinstance(node, ast.ClassDef):
                            doc = get_docstring(node)
                            if doc:
                                file_docs.append(f"### Class: `{node.name}`\n{doc}\n")
                                file_has_docs = True
                        elif isinstance(node, ast.FunctionDef):
                            doc = get_docstring(node)
                            if doc:
                                file_docs.append(
                                    f"### Function: `{node.name}`\n{doc}\n"
                                )
                                file_has_docs = True

                    if file_has_docs:
                        api_docs.extend(file_docs)

                except Exception as e:
                    print(f"Error parsing {filepath}: {e}")

    return "\n".join(api_docs)


if __name__ == "__main__":
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    api_docs_content = generate_api_docs(repo_root)

    docs_dir = os.path.join(repo_root, "docs")
    os.makedirs(docs_dir, exist_ok=True)
    output_path = os.path.join(docs_dir, "api_reference.md")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(api_docs_content)

    print(f"API documentation saved to {output_path}")
