#!/usr/bin/env python3
"""
Syncs API documentation from Python files to a single markdown file using AST.
"""

import ast
import os


def generate_docs(filepath: str) -> str:
    with open(filepath, "r", encoding="utf-8") as f:
        source = f.read()

    try:
        tree = ast.parse(source)
    except Exception:
        return ""

    out = f"## {filepath}\n\n"
    module_doc = ast.get_docstring(tree)
    if module_doc:
        out += f"{module_doc}\n\n"

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            out += f"### Class `{node.name}`\n"
            class_doc = ast.get_docstring(node)
            if class_doc:
                out += f"{class_doc}\n"
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    out += f"- **`{item.name}()`**\n"
            out += "\n"
        elif isinstance(node, ast.FunctionDef):
            out += f"### Function `{node.name}()`\n"
            func_doc = ast.get_docstring(node)
            if func_doc:
                out += f"{func_doc}\n"
            out += "\n"

    return out


def main() -> None:
    scan_dirs = ["ev_grid_oracle", "server"]
    doc_content = "# API Reference\n\nAutogenerated by `docs_sync.py`.\n\n"

    for d in scan_dirs:
        if not os.path.exists(d):
            continue
        for root, _, files in os.walk(d):
            for file in files:
                if file.endswith(".py") and file != "__init__.py":
                    filepath = os.path.join(root, file)
                    doc_content += generate_docs(filepath)

    os.makedirs("docs", exist_ok=True)
    out_path = os.path.join("docs", "api_reference.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc_content)
    print(f"Synced API docs to {out_path}")


if __name__ == "__main__":
    main()
