import ast
from pathlib import Path


def parse_file(filepath: str) -> str:
    with open(filepath, "r", encoding="utf-8") as f:
        source = f.read()

    try:
        tree = ast.parse(source)
    except Exception as e:
        return f"Error parsing {filepath}: {e}\n"

    output = []

    module_doc = ast.get_docstring(tree)
    if module_doc:
        output.append(f"## Module: `{filepath}`")
        output.append(f"{module_doc}\n")
    else:
        output.append(f"## Module: `{filepath}`")
        output.append("*(No module docstring)*\n")

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            output.append(f"### Class: `{node.name}`")
            doc = ast.get_docstring(node)
            if doc:
                output.append(f"{doc}\n")
            else:
                output.append("*(No class docstring)*\n")
        elif isinstance(node, ast.FunctionDef) or isinstance(
            node, ast.AsyncFunctionDef
        ):
            # Only document top level functions to avoid clutter, or public methods
            if not node.name.startswith("_"):
                output.append(f"#### Function: `{node.name}`")
                doc = ast.get_docstring(node)
                if doc:
                    output.append(f"{doc}\n")
                else:
                    output.append("*(No function docstring)*\n")

    return "\n".join(output)


def main():
    root_dir = Path(__file__).parent.parent
    docs_dir = root_dir / "docs"
    docs_dir.mkdir(exist_ok=True)

    output_path = docs_dir / "api_sync.md"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# API Documentation Sync\n\n")
        f.write("This file is automatically generated by `tools/docs_sync.py`.\n\n")

        for py_file in root_dir.rglob("*.py"):
            if (
                ".venv" in py_file.parts
                or "venv" in py_file.parts
                or ".cursor" in py_file.parts
                or "tests" in py_file.parts
            ):
                continue

            f.write(parse_file(str(py_file)))
            f.write("\n---\n\n")

    print(f"Generated API docs at {output_path}")


if __name__ == "__main__":
    main()
