name: AI PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - name: CodeRabbit AI PR Review
        uses: coderabbitai/coderabbit-pr-review@main
