name: Autofix Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  autofix:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    permissions:
      workflows: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run Ruff Format
        run: uv run --with ruff ruff format .
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Run Prettier
        run: npx prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "style: auto-format code"
